easy_admin:
  entities:
    Deals:
      class: App\Entity\Deals
      list:
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'} 