#index:
#    path: /
#    controller: App\Controller\DefaultController::index

contact:
    path:       /{_locale}/contact
    controller: App\Controller\ContactController::index
    requirements:
        _locale: en|fr|de